# k8s/deployment.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-lab-deployment # Deployment name
  labels:
    app: kube-lab-app
spec:
  replicas: 2 # Number of copies to run
  selector:
    matchLabels:
      app: kube-lab-app
  template:
    metadata:
      labels:
        app: kube-lab-app
    spec:
      containers:
      - name: app-container
        image: kube-lab-app:v1 # The local Docker image you built
        ports:
        - containerPort: 80 # This must match the port EXPOSEd in your Nginx Dockerfile (port 80)